version: '3'
services:
  wordpress:
    image: wordpress
    restart: always
    volumes:
        - './www/:/var/www/html'
    ports:
        - 82:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: observant
      WORDPRESS_DB_PASSWORD: observant
      WORDPRESS_DB_NAME: observant

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: observant
      MYSQL_USER: observant
      MYSQL_PASSWORD: observant
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    ports:
        - ${PHPMYADMIN_PORT:-8886:80}
    depends_on:
        - db
    links:
        - db:db
