version: '3'
services:
    www:
        image: nginx:alpine
        restart: on-failure
        env_file: .env
        networks:
            - default
            - reverse-proxy
        volumes:
            - './www/:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
networks:
    reverse-proxy:
        external:
            name: reverse-proxy
