version: '3'
services:
  wordpress:
    image: wordpress
    restart: always
    env_file: .env
    networks:
        - default
        - reverse-proxy
    volumes:
        - './www/:/var/www/html'
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: observant
      WORDPRESS_DB_PASSWORD: observant
      WORDPRESS_DB_NAME: observant

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: observant
      MYSQL_USER: observant
      MYSQL_PASSWORD: observantpass
      MYSQL_ALLOW_EMPTY_PASSWORD: '1'
networks:
    reverse-proxy:
        external:
            name: reverse-proxy
