version: '3'
services:
    www:
        image: php:apache
        restart: on-failure
        env_file: .env
        networks:
            - default
            - reverse-proxy
        volumes:
            - './www/:/usr/src/app'
            - './docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
networks:
    reverse-proxy:
        external:
            name: reverse-proxy
